dbt_etl_test:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DEV_ETL_TEST_HOST') }}"
      port: "{{ env_var('DEV_ETL_TEST_PORT', 5433) | as_number }}"
      user: "{{ env_var('DEV_ETL_TEST_USER', 'postgres') }}"
      pass: "{{ env_var('DEV_ETL_TEST_PASSWORD') }}"
      dbname: "{{ env_var('DEV_ETL_TEST_DB_NAME') }}"
      schema: dbt_opozden

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('PROD_ETL_TEST_HOST') }}"
      port: "{{ env_var('PROD_ETL_TEST_PORT', 5433) | as_number }}"
      user: "{{ env_var('PROD_ETL_TEST_USER', 'postgres') }}"
      pass: "{{ env_var('PROD_ETL_TEST_PASSWORD') }}"
      dbname: "{{ env_var('PROD_ETL_TEST_DB_NAME') }}"
      schema: analytics

  target: dev
