version: 2

models:
  - name: stg_local_titanic
    description: This model cleans up data from Titanic
    columns:
      - name: passenger_id
        description: Unique identifier of a passenger
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: sex
        description: Sex of a passenger
        tests:
          - accepted_values:
              values: ['male', 'female', null]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: character varying

      - name: age
        description: Age of a passenger
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

      - name: fare
        description: Price of the ticket
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double precision

      - name: embarked_at
        description: Station where the passenger was onboarded
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: character varying
          - accepted_values:
              values: ['Cherbourg', null, 'Queenstown', 'Southampton']

      - name: passenger_class
        description: Class of apartments
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

      - name: parents_children
        description: Number of parents or children aboard
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

      - name: siblings_spouses
        description: Number of siblings/spouses aboard
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

      - name: survived
        description: Dead/Alive
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean