version: 2

models:
  - name: top_3_popular_products_previous_month
    description: Top 3 most popular product sold for the previous month
    columns:
      - name: product_name
      - name: order_count
        description: total count of sold the product
  - name: most_sold_product_for_every_manager
    description: Product that was more frequently sold this month by Sales managers.
    columns:
      - name: sales_agent_name
        tests:
          - not_null
  - name: income_orders
    description: monthly report on total revenue and number of orders.
  - name: income_month_incremental
    description: calculate the percentage increase in income from month to month
  - name: sales_manager_discounts
    description: for each agent, using window functions, calculate the average amount of discount they give
  - name: sales_manager_discounts_above_avg
    description: using CTE, identify agents that provide discounts above the overall average.
